### ISSUE TITLE
想要个便携的方法，不知道有没有

### ISSUE THREAD

**Issue by otakustay** [ecomfe/promise#21]
我想要一个方法，签名如下：

```
{Promise} foo({Function} task)
```

这个方法能符合以下条件：

1. 函数返回普通值，则返回一个`resolve`的，提供的值为返回值
2. 函数抛出异常，则返回一个`reject`的，提供值为抛出的异常
3. 函数返回`Promise`，则直接返回这个`Promise`，或弄一个新的但与这个返回的`Promise`状态同步

有没有这样的方法？感觉`new Promise(executor)`本身很接近这个功能，但是不符合上面的第1点，必须等`resolve`或`reject`被调用

这样的一个方法很有用，在未知某个函数是否异步时作为代理调用搞成`Promise`对象都是这样的逻辑，其实代码也很简单：

```javascript
try {
    var returnValue = bar(args);
    return Promise.resolve(returnValue); // Promise.resolve会处理返回值是普通对象或Promise的差异性
}
catch (ex) {
    return Promise.reject(ex);
}
```

**Comment by Exodia** [comment]
这个 api 命名成invoke 吧.
