### ISSUE TITLE
IE10&11下，setImmediate方法调用报错

### ISSUE THREAD

**Issue by leowang721** [ecomfe/promise#24]
在PromiseCapacity.js中的line170附近

```javascript
capacity.invoke(function () {
    var callback;
    ...
```
在这之前实际上配置了capacity.invoke为setImmediate
实际上这里调用setImmediate === window.setImmediate是为真
但是使用时就直接抛异常了：调用的对象无效

经过简单的实验，发现似乎IE10~11的setImmedate绑定了自己的this为window，如果不是就抛异常……

因为这样的代码是不会抛异常的

```javascript
capacity.invoke.call(window, function () ... }
```

**Comment by Exodia** [comment]
ie10-11确实的 setImmedate 确实行为如此，不过很奇怪的是测试用例居然是100%过的。
