### ISSUE TITLE
增加静态事件

### ISSUE THREAD

**Issue by otakustay** [ecomfe/promise#5]
考虑在在`Promise`对象上增加事件`resolved`、`rejected`和`exception`

这是ER的`Deferred`对象被频繁要求的一个功能，需求是能在调试过程中看到错误信息

但是如果最终随着标准的`Promise`对象普及，这个事件事实上是会消失的，会形成一个非兼容性的变化，不能平稳过渡，因此对这一功能是否加入有所犹豫

这个希望和 @errorrik @leeight @Justineo @firede @wangyang0123 各位进行一下讨论，集中在几点：

1. 是否要考虑未来的平稳过渡，还是直接放弃向ES标准的过渡
2. 是否需要加这一功能
3. 是否要从实践规范或直接在实现上限制这一功能仅能用于调试
4. 没有这一功能，我们是否有更好地方法来实现各位T级不高的同学调试的需求

**Comment by otakustay** [comment]
@Exodia

参考这个吧：https://gist.github.com/domenic/9b40029f59f29b822f3b

一个通用的异常事件是很有必要的

**Comment by Exodia** [comment]
我想 api 上参考： https://github.com/petkaantonov/bluebird/#error-handling 
也是上面的链接引用到的。

```javascript

Promise.onPossiblyUnhandledRejection(function(error){
    throw error;
});
```

默认实现是调用 console.error(error) 打印错误到控制台，使用者可以调用 Promise.onPossiblyUnhandledRejection 覆盖默认异常处理函数。

**Comment by Exodia** [comment]
分解成两个子功能：

- 提供Promise.onPossiblyUnhandledRejection接口，用于对未处理的 rejection 做一些定制化操作

- 提供类似于window.onerror的 global event，这块需要做些兼容工作，打算放在下个小版本做

**Comment by otakustay** [comment]
这两者的区别是，一个是方法，一个是事件可以多handler？

**Comment by Exodia** [comment]
这里我主要搞不太清楚未来标准的实现方案趋势，所以打算提供2个实现，等未来标准确定后再做简单的改写：

实现第二种方案也需要在实现第一种方案的基础上去做，区别可能只是是否对外暴露接口。

而第二种挂在 window 的方案更符合目前未捕获错误处理的习惯。

所以分成了两步来走。

**Comment by otakustay** [comment]
第一种先实现吧，第2种如果可能造成与未来标准不兼容但正好一样使用了`onerror`的话，我感觉很危险，因为会没有办法做向后兼容，所以放在window上也建议换个事件名

**Comment by Exodia** [comment]
事件名肯定会换的，仅仅是举个例子说明下未捕获异常按目前习惯是全局的
